static const char mirc[]
  = "#define __mirc__ 1\n"
    "#define __MIRC__ 1\n"
    "#define __STDC_HOSTED__ 1\n"
    "//#define __STDC_ISO_10646__ 201103L\n"
    "#define __STDC_NO_ATOMICS__ 1\n"
    "#define __STDC_NO_COMPLEX__ 1\n"
    "#define __STDC_NO_THREADS__ 1\n"
    "#define __STDC_NO_VLA__ 1\n"
    "#define __STDC_UTF_16__ 1\n"
    "#define __STDC_UTF_32__ 1\n"
    "#define __STDC_VERSION__ 201112L\n"
    "#define __STDC__ 1\n"
    "\n"
    "/* Some GCC alternative keywords used but not defined in standard headers:  */\n"
    "#define __const const\n"
    "#define __const__ const\n"
    "#define __inline__ inline\n"
    "#define __restrict__ restrict\n"
    "#define __signed signed\n"
    "#define __signed__ signed\n"
    "#define __volatile volatile\n"
    "#define __volatile__ volatile\n";
